name: Deploy MultiK8s
on: 
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD) # Get the comment id 

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions 
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: |-
          docker build -t dancingdumpling/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dancingdumpling/react-test npm test
      
      #https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
      - name: Set Identity Provider 
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/580733139848/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-action-deployer@multi-k8s-352603.iam.gserviceaccount.com'

      - name: Set Project 
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-352603
      
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials 
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: australia-southeast1-a
      
      - name: Build 
        run: ../../deploy.sh
        shell: bash
