name: Deploy MultiK8s
on: 
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD) # Get the comment id 

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions 
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: |-
          docker build -t dancingdumpling/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dancingdumpling/react-test npm test
      
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project 
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-352603
      
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials 
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: australia-southeast1-a
      
      - name: Build 
        run: |-
          docker build -t dancingdumpling/multi-client:latest -t dancingdumpling/multi-client:${{ env.SHA }} ./client 
          docker build -t dancingdumpling/multi-server:latest -t dancingdumpling/multi-server:${{ env.SHA }} ./server
          docker build -t dancingdumpling/multi-worker:latest -t dancingdumpling/multi-worker:${{ env.SHA }} ./worker

      - name: Push 
        run: |-
          docker push dancingdumpling/multi-client:latest
          docker push dancingdumpling/multi-client:${{ env.SHA }}

          docker push dancingdumpling/multi-server:latest
          docker push dancingdumpling/multi-server:${{ env.SHA }}

          docker push dancingdumpling/multi-worker:latest
          docker push dancingdumpling/multi-worker:${{ env.SHA }}

      - name: Apply 
        run: |-
          kubectl apply -f ./k8s
          kubectl set image deployment/client-deployment client=dancingdumpling/multi-client:${{ env.SHA }}
          kubectl set image deployment/server-deployment server=dancingdumpling/multi-server:${{ env.SHA }}
          kubectl set image deployment/worker-deployment dancingdumpling/multi-worker:${{ env.SHA }}
